version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  lint-and-test:
    executor:
      name: node/default
    parameters:
      message:
        type: string
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/<< parameters.message >>
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run linter
          working_directory: ~/project/<< parameters.message >>
      - run:
          command: npm run test
          name: Run unit tests
          working_directory: ~/project/<< parameters.message >>
workflows:
  frontend:
    jobs:
      - lint-and-test:
          message: frontend
  backend:
    jobs:
      - lint-and-test:
          message: backend
