version: '2.1'
orbs:
  node: circleci/node@5.0.3
jobs:
  lint-and-test:
    executor:
      name: node/default
    parameters:
      directory:
        type: string
    steps:
      - checkout
      - node/install-packages:
          app-dir: ~/project/<< parameters.directory >>
          pkg-manager: npm
      - run:
          command: npm run lint
          name: Run linter
          working_directory: ~/project/<< parameters.directory >>
      - run:
          command: npm run test
          name: Run unit tests
          working_directory: ~/project/<< parameters.directory >>
      - when:
          condition:
            equal: [backend, << parameters.directory >>]
          steps:
            - run:
                command: npm run test:e2e
                name: Run end-to-end tests
                working_directory: ~/project/<< parameters.directory >>
workflows:
  frontend:
    jobs:
      - lint-and-test:
          directory: frontend
  backend:
    jobs:
      - lint-and-test:
          directory: backend
